### ISSUE TITLE
启动EurekaServiceApplication 报错

### ISSUE THREAD

**Issue by jacksunsong** [nobodyiam/spring-cloud-in-action#1]
兄弟，我把你的代码下载下俩后，按照你的指导 http://techshow.ctrip.com/archives/1699.html，先启动config-server，然后启动 EurekaServiceApplication ，启动Eureka server的时候报错 

com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused: connect
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar:1.19.1]
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27) ~[eureka-client-1.4.11.jar:1.4.11]
	at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:570) ~[jersey-client-1.19.1.jar:1.19.1]

能不能看看什么原因，我是新手，还请赐教哦

**Comment by nobodyiam** [comment]
估计是启动过程中需要向自己注册吧，但是自己还没启动好，会重试的，应该没啥关系。
